### ISSUE TITLE
How to load into maps

### ISSUE THREAD

**Issue by vos6434** [masagrator/PortalNXSideLoader#3]
I'm trying to get portal Mel to work, main menu and loading screens all work but the game loads portal 2 maps instead of Mel's.
![Portal_2_20220821_092106_00](https://user-images.githubusercontent.com/21976486/185782691-43c8998c-60ff-4338-9903-fb9c3379abe0.jpg)
![Portal_2_20220821_092136_00](https://user-images.githubusercontent.com/21976486/185782693-5afe41fe-ee00-48fa-b9d7-76fd28f104a6.jpg)

**Comment by vos6434** [comment]
I was blind and didn't see new game, unfortunately loading into the first chapter crashes the game. Extracted maps materials folder comes with .vhv files, where do I place them?

**Comment by masagrator** [comment]
> I was blind and didn't see new game, unfortunately loading into the first chapter crashes the game. Extracted maps materials folder comes with .vhv files, where do I place them?

Don't touch those files. They are part of BSP and game doesn't even try to load them outside of BSP.
