### ISSUE TITLE
Custom sounds are not working on Portal 1 + another strange issue.

### ISSUE THREAD

**Issue by LittlePlanetCD** [masagrator/PortalNXSideLoader#4]
So, i was taking my time early in the morning to try out Sideloader. It's really good, but I found two issues with it... Lemme explain.

Basically, I was trying to port over ERROR, a really good horror mod for Portal 1 using this method. I basically just copied over the entire mod folder into the romfs/portal folder to get it to load. however, i found some issues.

1: Maps causing an instant crash.
- I do not know what the actual problem is with this, as i tested the bare minimum to get these maps to load, which were the cfg, maps, materials, scripts, and sounds folders. using only those i got the maps to load (with bugged textures). I have a feeling its related to the models or resource folder, but idk for sure. [minor note about the bugged textures thing, since its a known issue: this kind of problem is not occurring using the repack game.zip method before Sideloader was a thing. im certain you looked into this a lot already, but i wanted to point out this detail.]. basically, just copying and pasting the entire mod will cause this to happen. it's not specific to ERROR at all, it also happens to other mods like Project Alpha.

2. custom sounds do not work.
- using the bare minimum to load ERROR, which were the cfg, maps, materials, scripts, and sounds folders, I could get into the game perfectly fine. except there was a glaring issue [aside from the textures]: No custom sounds were working. It's strange, because with the repack game.zip method, they work just fine. I double-checked to make sure that the mod had its sounds in there, and it did. but the custom radio music that was supposed to play was completely gone, like silent. some other triggered sounds, like the chair room static, also did not play. it was really strange.

**Comment by masagrator** [comment]
I will check it in few days.
Did you check if all file and folder names in mod are lower case?

**Comment by LittlePlanetCD** [comment]
i can confirm all files in ERROR are lowercase.

**Comment by masagrator** [comment]
> i can confirm all files in ERROR are lowercase.

And I can confirm not all files are.  ¯\\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/8557858/204048814-fb4034be-2d99-4ffd-86c9-7c6832d608aa.png)

Fixing this doesn't solve the issue though.

**Comment by masagrator** [comment]
Well, found first issue.

```
Thread 1 "Thread_ID=3480" hit Breakpoint 4, 0x0000006d67f19760 in ?? ()
=> 0x0000006d67f19760:  4b 16 00 94     bl      0x6d67f1f08c
(gdb)
$419 = 0x6d67f25048 "rom:/nxcontent/portal/downloadlists/errbackground.lst"
$420 = 0x35a89d26b9 "wt"
```
Mod for whatever reason tries to open file for writing, which is not possible. I didn't include any protection against that. I will try to redirect any call that allows writing to default function.

**Comment by masagrator** [comment]
https://github.com/masagrator/PortalNXSideLoader/commit/1aac5cef4919096e6e1e8fd42b19205d4f71c3ae

Yeah, at least now mod loads normally. Still there are texture issues (which seems similar to what we have in case of Portal 2 and I guess solution will be the same), and no custom audio.

**Comment by masagrator** [comment]
So yeah, as in Portal 2 unpacking `materials` from maps solves texture issues

![2022112609361600](https://user-images.githubusercontent.com/8557858/204079920-f45d531b-5b31-4dd3-8957-cf054decc248.jpg)

**Comment by masagrator** [comment]
I think I have found a bug that idk why happens, but it happens.

It seems using `stat` clears out path buffer if it detects that file exists - for whatever reason - and since I'm passing it twice, when first time it detects it's correct, by second time it's detected as wrong. This seems didn't affect anything EXCEPT custom sound files and some materials that were shown as broken before. So thanks to you I think I've found the main issue why this shit happened.

So now there is no need to unpack materials and sounds anymore.

I still need to test if this won't break anything in Portal 2 before releasing.

**Comment by masagrator** [comment]
Check now new release and follow mod installation tutorial from README

https://github.com/masagrator/PortalNXSideLoader/releases/tag/1.3

**Comment by LittlePlanetCD** [comment]
alright, i'll take a look.

**Comment by LittlePlanetCD** [comment]
I'm gonna do a full playthrough of a mod for testing, although there's one thing i wanna ask.

Is there a way to replace the valve intro? i'm curious, because my custom one isnt replacing the one from Portal.

**Comment by masagrator** [comment]
Intro path is hardcoded to `(nxcontent/)`portal/z/p1_intro.mkv

So you must convert it to h264/aac and pack it to mkv (for example with mkvtoolnix)

To test it you can take valve.mkv from portal/media that doesn't have nvidia logo and put it in correct folder with correct name

**Comment by LittlePlanetCD** [comment]
ohhh, interesting. so it has to be in the nxcontent folder?

I did notice that mods are supposed to be placed in nxcontent/, although i found out that it going into the root portal/ folder also works. I haven't experienced a side effect aside from saves not working regardless of where the mod is installed.

I'm not sure how to fix that, though.

**Comment by masagrator** [comment]
nxcontent allows us to separate big mods from small ones like translation mods that should go to their original folders. Separation is just for convenience. In case of Portal 2 matter is more complicated, but it's solved already.

**Comment by LittlePlanetCD** [comment]
actually, the saving issue not a mod issue.

it seems like at any point the sideloader detects *any* modified file in the romfs, saves are just broken. they work for the session you're in, but once you close, they are just *gone*.

running sideloader without *anything* in the romfs folder has saves working fine. I only have materials, models, and sounds in my romfs folder and its affecting save data.

**Comment by masagrator** [comment]
Yeah, just checked that with new session my saves are gone. :D I will try to look at it.

**Comment by LittlePlanetCD** [comment]
alright, thank you.

if it's okay, I have discord, we can contact each other there to further figure out this saving issue, and close this one since the original issue has been fixed. is that okay?

**Comment by masagrator** [comment]
OK. My Discord is MasaGratoR#1567
